name: Build and deploy Pro on AWS and CleverCloud

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement cible sur lequel déployer l'application"
        default: "integ"
        type: choice
        options:
          - integ
          - staging
          - prod
      deploy-to-clever:
        description: "Est-ce qu'il faut également déployer également sur Clever Cloud ?"
        default: 'non'
        type: choice
        options:
          - oui
          - non
  workflow_call:
    inputs:
      environment:
        description: "Environnement cible sur lequel déployer l'application"
        type: string
      deploy-to-clever:
        description: "Est-ce qu'il faut également déployer également sur Clever Cloud ?"
        type: string
    secrets:
      CLEVER_TOKEN:
        required: true
      CLEVER_SECRET:
        required: true

concurrency:
  group: pro-${{ github.ref }}-${{ inputs.environment}}-1
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  build_and_deploy:
    runs-on: buildjet-4vcpu-ubuntu-2204
    environment: ${{ inputs.environment }}
    env:
      APPLICATION: 'pro'
      PRODUCT: lite
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      LITE_COMMON_APP_CONFIG_SECRET_ARN: ${{ vars.LITE_COMMON_APP_CONFIG_SECRET_ARN }}
      LITE_PRO_APP_CONFIG_SECRET_ARN: ${{ vars.LITE_PRO_APP_CONFIG_SECRET_ARN }}
      API_PORT: ${{ vars.LITE_PRO_API_PORT }}
      TASK_CPU: ${{ vars.LITE_PRO_TASK_CPU }}
      TASK_MEMORY: ${{ vars.LITE_PRO_TASK_MEMORY }}
      DB_CONFIG_SECRET_ARN: ${{ vars.LITE_PRO_DB_CONFIG_SECRET_ARN }}
      DB_DATAWAREHOUSE_CONFIG_SECRET_ARN: ${{ vars.LITE_PRO_DATAWAREHOUSE_DB_CONFIG_SECRET_ARN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Exécuter les steps communs
        uses: ./.github/actions/common-deploy
        with:
          environment: ${{ env.ENVIRONMENT }}
          application: ${{ env.APPLICATION }}
          product: ${{ env.PRODUCT }}
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          aws-region: ${{ env.AWS_REGION }}
          clever-token: ${{ secrets.CLEVER_TOKEN }}
          clever-secret: ${{ secrets.CLEVER_SECRET }}
          deploy-to-clever: ${{ inputs.deploy-to-clever }}
          github-sha: ${{ github.sha }}
